##intitialize the docker-compose version
version: '3.4'

#add the networks:
networks:
  stocklistingnetwork:



#add the services:
  
services:
  
##add the stocklisting image

#add the mysql image
     stocklistingdb:
        container_name: stocklistingdb
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
            - 8002:1433
        environment:
         - ACCEPT_EULA=Y
         - MSSQL_SA_PASSWORD=Password123
        networks:
            - stocklistingnetwork
        

     stocklisting:
        image: ${DOCKER_REGISTRY-}stocklisting
        container_name: stocklistingapp
        build:
            context: .
            dockerfile: StockListing/Dockerfile
        ports:
            - 8081:80
        depends_on:
         - stocklistingdb
        networks:
         - stocklistingnetwork


